### ISSUE TITLE
Move "trailing comma rule for annotations" in checkstyle_semantics to checkstyle_semantics_strict

### ISSUE THREAD

**Issue by kathleenkusworo** [liftwizard/liftwizard#2520]
https://github.com/liftwizard/liftwizard/blob/main/liftwizard-utility/liftwizard-checkstyle/src/main/resources/checkstyle-configuration-liftwizard-semantics.xml#L95-L97

Consider moving this rule to "strict", as this clashes with prettier. Prettier only adds trailing commas in arrays when the array is long enough to be split into multiple lines. Otherwise, prettier will always try to consolidate the array into one line and not add a trailing comma.

**Comment by motlin** [comment]
A few thoughts

- This rule seems like a formatting rule, so maybe the formatting profiles would be more appropriate 
- This rule can be configured with always, never, and ignore. One option would be to configure it with ignore in the regular profile and always in the strict profile 
- The point of a trailing comma is to minimize git history churn when adding an additional element. This only applies when spread across several lines. Maybe we should request additional options be added to Checkstyle, for "always when spread across multiple lines"

**Comment by kathleenkusworo** [comment]
> This rule seems like a formatting rule, so maybe the formatting profiles would be more appropriate
I think this makes sense especially since prettier considers it a formatting issue. We know to not turn on checkstyle-formatting if we have other formatters (like prettier, gjf) turned on, so it feels like a natural solution.

> The point of a trailing comma is to minimize git history churn when adding an additional element. This only applies when spread across several lines. Maybe we should request additional options be added to Checkstyle, for "always when spread across multiple lines"
Makes sense, I'll follow up
